jobs:
- job: runOnCustomMachines # = custom machines
  pool:
    name: Default
  container:
    image: rmetzger/flink-ci:5-ubuntu-amd64
  timeoutInMinutes: 120
  steps:
  # Azure pipelines can only evaluate conditions with the build repo name in the steps.
  # if the repo == "flink-ci/flink", we execute the steps
  - task: Maven@3
    condition: eq(variables['Build.Repository.Name'], 'flink-ci/flink')
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean install'
      timeoutInMinutes: 120

- job: runOnAzure
  pool:
    vmImage: 'ubuntu-latest'
  container:
    image: rmetzger/flink-ci:5-ubuntu-amd64
  timeoutInMinutes: 240
  steps:
  # Azure pipelines can only evaluate conditions with the build repo name in the steps.
  # if the repo != "flink-ci/flink", we execute
  - task: Maven@3
    condition: not(eq(variables['Build.Repository.Name'], 'flink-ci/flink'))
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean install'
      timeoutInMinutes: 240
